### ISSUE TITLE
Onboarding: honeyswap liquidity

### ISSUE THREAD

**Issue by 0xGabi** [1Hive/gardens#12]
Add an explanatory text: `Set the initial equivalence between HNY and TKN by specifying the initial Honeyswap liquidity for the HNY/TKN pair.`

## Configure the HNY / TKN pair
    1. Set the amount of HNY in stable value (required, number of stable token equivalent to at least 100 USD worth of HNY)
        1. Add a help bubble with the following text: `You must specify an amount worth at least 100 USD`
    2. Configure the amount of TKN tokens (required)
        1. Add a help bubble with the following text: `The initial relationship between HNY <> TKN depends on the number of tokens configured.`

**Comment by sembrestels** [comment]
I propose to make this page a bit different. The equality of GDN and HNY should be the first thing people see, setting the default to 100 GDN in one side and $100 in HNY on the other. The amout in HNY can be specified in USD as well, using a dropdown. You can always see the initial price and initial added liquidity.

![HNY liquidity page](https://user-images.githubusercontent.com/931684/123144941-8e098380-d45c-11eb-9d75-5d8b655a5327.png)

**Comment by twell-s** [comment]
Made some adjustments on the figma @sembrestels; is this what we need?

**Comment by 0xmiel** [comment]
@sembrestels @0xGabi we especially need to clarify *why* we require initial liquidity on honeyswap.

Thinking about it, I would lean towards making it opt-in by default -- rather than a hard requirement -- and explain why/how this helps fund public goods like Gardens.

**Comment by 0xGabi** [comment]
From our latest Sprint Planning:

We agree to do a much better job explaining **WHY** the initial liquidity is needed. Make sure to keep it clear.


There are some technical aspects of the system that function better, like the oracle. If you are going to recalibrate the Action and Challenge stable amounts.


@pglavin2 suggested a synergistic idea of gave scholarship for those that can’t afford to create a new Garden.

@GriffGreen suggests that maybe make sense to have it tight to a liquidity mining program.
