### ISSUE TITLE
Gardens landing page

### ISSUE THREAD

**Issue by fioreb** [1Hive/gardens#122]
Here is the design with the banner that the majority prefer to use:

https://www.figma.com/file/CCNEARX00L21tCroawNaas/Gardens-MVP1?node-id=310%3A1048

The text of the buttons is a placeholder based on what we discuss in the meeting, we can modify it.

You can find the assets attached here:
[https://app.zenhub.com/files/353881841/26e5bb2b-e7e0-4a89-ba93-ef8b5dd7b8c9/download](https://app.zenhub.com/files/353881841/26e5bb2b-e7e0-4a89-ba93-ef8b5dd7b8c9/download)

(the banner for mobile and tablet is missing but I'll add them today)

**Comment by fioreb** [comment]
Attached here you can find the banners for mobile and tablet:

[https://app.zenhub.com/files/353881841/fc8662f7-e8a7-4be3-af15-6d144420d2de/download](https://app.zenhub.com/files/353881841/fc8662f7-e8a7-4be3-af15-6d144420d2de/download)

**Comment by fabriziovigevani** [comment]
closed by https://github.com/1Hive/honey-pot/pull/469
