### ISSUE TITLE
Incorrect wrapped token icon being displayed

### ISSUE THREAD

**Issue by CurlyBracketEffect** [1Hive/gardens#128]
On the main page, there is no icon for the unwrapped token amount, and the unwrapped icon is shown for the wrapped token

![Screen Shot 2021-05-29 at 5 39 26 PM](https://user-images.githubusercontent.com/25679386/120085304-07ec5e00-c0a5-11eb-8ae0-d95f612bf032.png)

**Comment by fabriziovigevani** [comment]
Ah this component doesn't display the token icon, just the symbol. And as far as i can tell, the wrapped token symbol was set as 🔆

![Screen Shot 2021-05-31 at 17 42 56](https://user-images.githubusercontent.com/22663232/120240727-ab6d7800-c237-11eb-93a7-c2dab5432efe.png)

**Comment by 0xGabi** [comment]
Ouch, that was me indeed. I choose that as the symbol for the Garden 😅
