### ISSUE TITLE
Link to covenant redirects to the Gardens page

### ISSUE THREAD

**Issue by CurlyBracketEffect** [1Hive/gardens#129]
When I click to view the covenant before signing. It tries to open https://gardens-rinkeby.1hive.org/#/covenant, but then redirects to https://gardens-rinkeby.1hive.org/#/home

It also does not open in a new tab but rather refreshes the current page I am on.

![Screen Shot 2021-05-29 at 5 42 20 PM](https://user-images.githubusercontent.com/25679386/120085358-80ebb580-c0a5-11eb-83a0-2a3c4931a1a2.png)

**Comment by fabriziovigevani** [comment]
Closed by https://github.com/1Hive/honey-pot/pull/498

Thanks for reporting @CurlyBracketEffect !
