### ISSUE TITLE
Showing Nectar symbol for balance on the proposal page

### ISSUE THREAD

**Issue by CurlyBracketEffect** [1Hive/gardens#131]
It is also showing a different icon in the top right for Balances

![Screen Shot 2021-05-29 at 5 36 54 PM](https://user-images.githubusercontent.com/25679386/120085263-97ddd800-c0a4-11eb-9afe-b14e5b90848a.png)

**Comment by fabriziovigevani** [comment]
What's the NECTAR symbol you are referring to? Could you post a screenshot? 

Regarding the icon for the balances, that token is the wrapped token. If no icon was set for `token` in the dao-list then it uses a default one. We can use the same one that was set for the `wrappableToken` (`BRIGHT`) but that may cause more confusion.

**Comment by fioreb** [comment]
I think that image should be the token icon as we have it for 1Hive the HNY icon, is that what you are suggesting?

**Comment by CurlyBracketEffect** [comment]
This is for BrightDAO. In the picture is depicted the token logo for NCTR which belongs to the Beezus DAO. I believe there was a mixup when @0xGabi uploaded the assets. I included a logo that is the Bright symbol but with a different colour to represent the wrapped version of our token.

**Comment by fabriziovigevani** [comment]
Ah i see, thanks for clarifying. I thought you didn't provide a logo for the wrapped version. The NCTR token logo is actually a default one we use when no logo is provided.

@0xGabi do you have the wrapped icon logo version to include in dao-list?
