### ISSUE TITLE
All transaction processing screens show Honey symbol

### ISSUE THREAD

**Issue by CurlyBracketEffect** [1Hive/gardens#132]
When I go to wrap a token it is showing the icon for wrapped Honey instead of the icon I uploaded for Bright token

![Screen Shot 2021-05-28 at 11 19 37 PM](https://user-images.githubusercontent.com/25679386/120085242-695ffd00-c0a4-11eb-94a4-f7ae6d1bb61d.png)

**Comment by rperez89** [comment]
This one i think is fine since is a 1hive common image like the bee being the loading animation etc

**Comment by CurlyBracketEffect** [comment]
Right...makes sense for now. I am just wondering since this is a "white label" type framework if these images could also be customized; the loading bee included. Could we replace that with an animated Bright symbol for example? and if we got an image made for the screen displayed here, could we replace that as well?

**Comment by 0xGabi** [comment]
We can consider using the Garden branding logo.
