### ISSUE TITLE
Are we able to adjust the amount of BRIGHT required to collateralize a proposal?

### ISSUE THREAD

**Issue by CurlyBracketEffect** [1Hive/gardens#133]
![Screen Shot 2021-05-30 at 1 40 03 AM](https://user-images.githubusercontent.com/25679386/120093416-11e38080-c0e8-11eb-849b-8ef43fb4ca5e.png)

**Comment by fabriziovigevani** [comment]
Yeah you can adjust it by interacting directly with the Covenant smart contract, though not UI yet for that. Note also that there's a collateral updater contract which updates the collateral amounts relative to a preconfigured stable value.

**Comment by CurlyBracketEffect** [comment]
Is there any documentation for how this parameter would be changed and is there anything else like this that can be changed that should be documented?

Also, is the covenant contract controlled by the DAO itself? Would this need to be a vote directly on the Arragon platform in order to change this parameter?

**Comment by fabriziovigevani** [comment]
Don't think there's documentation yet on how you can change this amounts. Will make sure we have.

About your second question, yes the covenant's permissions are granted to the voting app of the DAO so any change will have to be voted on by members.

**Comment by 0xmiel** [comment]
@CurlyBracketEffect this parameter is configurable pre-deployment

The documentation is here
https://1hive.gitbook.io/gardens/users/create-a-garden-with-scripts#configure-garden-parameters

It's referred to as the `actionAmount` in the `params-<network>.json`

If you're thinking of changing it, I would recommend changing the `challengeAmount` too - makes sense for them to be symmetrical

**Comment by 0xGabi** [comment]
I will close this one. We already had an issue to add documentation on how to update configuration parameters.
