### ISSUE TITLE
When on profile page there is no navigation back to proposal screen

### ISSUE THREAD

**Issue by CurlyBracketEffect** [1Hive/gardens#134]
![Screen Shot 2021-05-30 at 1 49 42 AM](https://user-images.githubusercontent.com/25679386/120093636-9be01900-c0e9-11eb-8a18-c430007a549c.png)

On the main proposal screen, I can click on my address to find options to go to "My Profile" or to the "Collateral Manager". I can also click on the BRIGHT symbol in the top left to reload the page.

If I click on "My Profile", I am brought to the profile page, but now when I click on my address, I do not have the option to get to my "Collateral Manager". I would expect that to still be present.

Also, the symbol in the top left is replaced with the Gardens type logo and redirects to the page with all the GardenDAOs on it. I would expect the BRIGHT symbol to be there and that it would bring me back to the main proposal screen.

![Screen Shot 2021-05-30 at 1 49 22 AM](https://user-images.githubusercontent.com/25679386/120093629-8d91fd00-c0e9-11eb-9be5-5f54ba8ca13a.png)

**Comment by laurenluz** [comment]
+1 on this issue. I think the UI could really improved by having the tree structure at the top say "Covenant  Proposals   Get GIV token ... etc."

also I don't think "stake honey" is the best way to describe an external link to celeste

Maybe just "Covenant   Proposals   Honeyswap   Celeste"

![image](https://user-images.githubusercontent.com/75490971/122692060-3bc42a80-d1f0-11eb-99e1-80aa5e8b5054.png)

**Comment by Chimdalu-Ofoegbu** [comment]
> +1 on this issue. I think the UI could really improved by having the tree structure at the top say "Covenant Proposals Get GIV token ... etc."
> 
> also I don't think "stake honey" is the best way to describe an external link to celeste
> 
> Maybe just "Covenant Proposals Honeyswap Celeste"
> 
> ![image](https://user-images.githubusercontent.com/75490971/122692060-3bc42a80-d1f0-11eb-99e1-80aa5e8b5054.png)
