### ISSUE TITLE
We currently don't have a bug bounty program

### ISSUE THREAD

**Issue by CurlyBracketEffect** [1Hive/gardens#136]
We don't have a Bug Bounty program yet, but it has a link in the footer that leads to 1Hive bounty program

![Screen Shot 2021-05-30 at 2 04 55 AM](https://user-images.githubusercontent.com/25679386/120093960-91268380-c0eb-11eb-9532-6ab6d5a51485.png)

**Comment by rperez89** [comment]
in which dao is this happening?

**Comment by CurlyBracketEffect** [comment]
BrightDAO

**Comment by fabriziovigevani** [comment]
https://github.com/1Hive/dao-list/pull/32
