### ISSUE TITLE
Discord link expired

### ISSUE THREAD

**Issue by CurlyBracketEffect** [1Hive/gardens#137]
The link for Discord in the footer is expired. I must have put a 24-hour link in the JSON file by accident. Here is an updated link that should never expire: https://discord.gg/Wx63jaYa2Z

![Screen Shot 2021-05-30 at 2 07 45 AM](https://user-images.githubusercontent.com/25679386/120094042-072aea80-c0ec-11eb-95ab-4658730619ad.png)

**Comment by rperez89** [comment]
in which Garden is this happening?

**Comment by CurlyBracketEffect** [comment]
BrightDAO

**Comment by fabriziovigevani** [comment]
closed by https://github.com/1Hive/dao-list/pull/32
