### ISSUE TITLE
Guide on how to create a new Garden

### ISSUE THREAD

**Issue by 0xGabi** [1Hive/gardens#14]
As a summoner, I want clear documentation on how to create a new Garden.

**Comment by 0xGabi** [comment]
@sachayves what you think of taking a similar approach to Gnosis Auction documentation to explain how to grow a Garden: https://gnosis-auction.eth.link/#/docs#topAnchor

**Comment by sachayves** [comment]
I like it! First impression is that the structure maps quite nicely. Is that what you meant?

**Comment by 0xGabi** [comment]
Yes, exactly. I think a simple website that does a good job of explaining why growing a Garden. And that has two guides: 
1. That showcases how to interact with an existing Garden (create a proposal, sign the agreement, etc). Similar to: https://gnosis-auction.eth.link/#/docs/participate-as-a-bidder#topAnchor
2. How to create a new Garden (at first we can just explain how to run a hardhat script to do it, like: https://gnosis-auction.eth.link/#/docs/participate-as-auctioneer#topAnchor)

**Comment by 0xGabi** [comment]
I'll close this one and replace by the general documentation on Gardens (#100) and the specific docs on how to create a Garden using hardhat scripts (#94).

We can think about a more in depth documentation once we have a Garden wizzard.
