### ISSUE TITLE
Can't click to sign the covenant

### ISSUE THREAD

**Issue by laurenluz** [1Hive/gardens#140]
Testing both Giveth and Beezu

[image.png](https://images.zenhubusercontent.com/5fdfac16a58523a866ddb68d/e32c8ccd-8340-4f74-8b22-a84d26facc2e)

![image.png](https://images.zenhubusercontent.com/5fdfac16a58523a866ddb68d/29abff59-abe9-41d3-b6fb-dcf20bf0424d)

**Comment by fabriziovigevani** [comment]
Ah you need to click on the checkbox first. We'll highlight it a little bit more as others have missed this as well.

**Comment by fabriziovigevani** [comment]
closed by 1Hive/honey-pot#500

**Comment by laurenluz** [comment]
oh wow yeah, I didn't even notice it until you pointed it out....

also perhaps you could also changing the wording to "I agree to the the Giveth Manifesto by laws and community code of behaviour"... then it would be more clear to the user that they are checking the box to agree
