### ISSUE TITLE
Onboarding: Voting settings

### ISSUE THREAD

**Issue by 0xGabi** [1Hive/gardens#148]
1. voteDuration
2. voteSupportRequired
3. voteMinAcceptanceQuorum
4. delegatedVotingPeriodDays
5. voteQuietEndingPeriodDays
6. voteQuietEndingExtensionDays
7. voteExecutionDelayDays

**Comment by 0xGabi** [comment]
We discuss having an Advanced mode where we show the extra configuration parameters.

**Comment by GriffGreen** [comment]
Making and Advanced Setting is exactly what the TEC is doing for the Dashboard... I reached out to @0xmiel to sync on some of this work so we can at the very least use the same names, and potentially even combine efforts.

Our Commons Config Dashboard will be used to educate the community about the parameters BEFORE the DAO is launched by engaging them to propose and vote on the parameters...  so this is a slightly different use case then just having one dev deploying the initial settings... But it is mostly the same! 

Especially for dV!

The Question is... should we just work with you to design it or let you do it and copy it, or you let us do it and copy us!

**Comment by GriffGreen** [comment]
I really like this graph for instance... 

![Screen Shot 2021-06-20 at 7 04 08 PM](https://user-images.githubusercontent.com/14945613/122694389-7607e900-d23d-11eb-86e4-0ed951d7486d.png)

We have some cool ideas for visualizing the time pieces of this app as well
