### ISSUE TITLE
Onboarding: Conviction Voting settings

### ISSUE THREAD

**Issue by 0xGabi** [1Hive/gardens#149]
Explanation and structure of the following fields:

1. halfLifeHours
2. maxRatio
3. minThreshold
4. minActiveStakePct

There should be a tool to simulate the results by modulating the above parameters. 

- [Latest jupiter notebook that Sem did for Conviction Voting.](https://colab.research.google.com/drive/159f6w8FhLz4zi0FROdamkUpUWCxye3Uu#scrollTo)

Consider reusing some of the following examples:

1. [Conviction half-life](https://www.desmos.com/calculator/w2jgqtqmwj)
2. [Conviction threshold](https://www.desmos.com/calculator/o1y3mkdlxd)
3. [Conviction + Threshold all-together](https://www.desmos.com/calculator/6w6wemlwl9](https://www.desmos.com/calculator/6w6wemlwl9)
4. [ABC common stack simulation](https://commonsstack.org/abc#simulation)

**Comment by 0xGabi** [comment]
We discuss having an Advanced mode where we show the `minActiveStakePct`. Otherwise, we only show the first three parameters.

**Comment by GriffGreen** [comment]
Making and Advanced Setting is exactly what the TEC is doing for the Dashboard... I reached out to @0xmiel to sync on some of this work so we can at the very least use the same names, and potentially even combine efforts.

Our Commons Config Dashboard will be used to educate the community about the parameters BEFORE the DAO is launched by engaging them to propose and vote on the parameters...  so this is a slightly different use case then just having one dev deploying the initial settings... But it is mostly the same! 

Especially for dCV!

The Question is... should we just work with you to design it or let you do it and copy it, or you let us do it and copy us!

**Comment by GriffGreen** [comment]
I hope you will be inspired by some of these links: 

Commons Simulator: http://sim.commonsstack.org/

Initial work for the dashboard: https://hackmd.io/Hj7pp7ZTQGmROC6zNDD1tg

**Comment by 0xGabi** [comment]
Thanks for sharing @GriffGreen.

@fioreb you should have the above documents in mind for the Conviction Voting settings as well.
