### ISSUE TITLE
Onboarding Settings: graph UI library research

### ISSUE THREAD

**Issue by 0xGabi** [1Hive/gardens#190]
Analyze current graph solution of Aragon UI. If it's not a good fit, consider other alternatives.

**Comment by sembrestels** [comment]
[This is the library](https://github.com/1Hive/tulip-frontend/tree/master/src/components/LineChart) @famole used for tulip. It looks like a good fit, let's use it for now.

**Comment by PJColombo** [comment]
Hey guys, I'm bumping this issue.
I just remember a cool React library called [nivo](https://nivo.rocks/) that has cool graph components like this [one](https://nivo.rocks/line) . Maybe we can use it in case fabi's library isn't a good fit. If not, maybe it might be useful for something else in the future :)
