### ISSUE TITLE
Onboarding Settings: create a prototype with the graphs we will use

### ISSUE THREAD

**Issue by 0xGabi** [1Hive/gardens#191]
Create two Jupiter notebooks:
- For the Issuance app
- For the Conviction Voting app

**Comment by GriffGreen** [comment]
For CV, make sure to see: https://hackmd.io/Hj7pp7ZTQGmROC6zNDD1tg

And 

https://sim.commonsstack.org

**Comment by sembrestels** [comment]
Here are the models:
* [Conviction Voting](https://colab.research.google.com/drive/1sT28zznQA_fMaQ_nIG6JhIVoOkV5Lx2a)
* [Dynamic Issuance](https://colab.research.google.com/drive/1vpiqGPgUEa7wk3ibIkyFGnoP3rfIp3Nb#scrollTo=O8EdvSbNZz5z)
