### ISSUE TITLE
Suggestion: make entire proposal clickable so that it is more intuitive to support proposals

### ISSUE THREAD

**Issue by laurenluz** [1Hive/gardens#193]
It's not intuitive imo to have to click "..." --> "details" in order to support a proposal

![image.png](https://images.zenhubusercontent.com/5fdfac16a58523a866ddb68d/04344934-9730-4574-9512-80c747831c48)

**Comment by 0xmiel** [comment]
@laurenluzto be clear, you can also click on the name of the proposal (although this is slightly better, it's still not intuitive/obvious for a first-timer)

do you have any immediate suggestions?

**Comment by fabriziovigevani** [comment]
We can definitely make the whole card clickable as suggested.

**Comment by 0xmiel** [comment]
@fabriziovigevani the only worry I have here is inadvertent clicking when scrolling on mobile

**Comment by laurenluz** [comment]
@0xmiel @fabriziovigevani maybe we can just have the name of the proposal bolded and underlined? underlined titles always look click-able to me 😄

**Comment by fabriziovigevani** [comment]
> @fabriziovigevani the only worry I have here is inadvertent clicking when scrolling on mobile

That's a good point, we could make it so that in mobile you only need to click name or action button but it's not the prettiest solution.

> @0xmiel @fabriziovigevani maybe we can just have the name of the proposal bolded and underlined? underlined titles always look click-able to me 😄

Yes that's something we could possible do, though i would be a bit concerned on how it would look 😅 cc. @fioreb

**Comment by fioreb** [comment]
I agree as we have it now is not the most intuitive way.

Since the (...) button was created keeping in mind that maybe in the future we will have more actions and for the moment the only thing that we could do is go to proposal's details, maybe we can remove that button and make the card clickable.

I agree for mobile could lead to unwanted clicking, so maybe for that case maybe we can make only the title clickable. But at the same time, I think the user is used to scroll throw cards without clicking them, so maybe this is not a problem 😅

**Comment by 0xmiel** [comment]
> @0xmiel @fabriziovigevani maybe we can just have the name of the proposal bolded and underlined? underlined titles always look click-able to me 😄

As a minimum viable fix, I like this suggestion. Even just underlined could do the trick. Thoughts @fioreb ?

**Comment by fioreb** [comment]
> > maybe we can just have the name of the proposal bolded and underlined? underlined titles always look click-able to me 😄
> 
> As a minimum viable fix, I like this suggestion. Even just underlined could do the trick. Thoughts @fioreb ?

I did a quick try and yes I think it can work!

<img width="967" alt="Screen Shot 2021-07-01 at 13 54 31" src="https://user-images.githubusercontent.com/61423083/124161609-fe735e80-da73-11eb-8fc0-bc276ca11f2f.png">

**Comment by 0xmiel** [comment]
Wonderful :)

**Comment by fabriziovigevani** [comment]
Yes, will work on it!

**Comment by fabriziovigevani** [comment]
https://github.com/1Hive/honey-pot/pull/520
