### ISSUE TITLE
Allow individual gardens to add their own forum links

### ISSUE THREAD

**Issue by laurenluz** [1Hive/gardens#194]
This "Giveth Forum" external link goes to the 1hive forum.. would be good ensure that the right forum link is in that DAO's garden

![image.png](https://images.zenhubusercontent.com/5fdfac16a58523a866ddb68d/2ab586d3-dd61-4428-ae80-8547fa9b403a)

**Comment by fabriziovigevani** [comment]
In this case there's no forum link provided in the dao-list library under the Giveth garden data, so it's using the default (1Hive's). The problem with checking corresponding forum link is that Agave for example uses 1hive's forum as well so i wouldn't see a way to do this check without handling special cases

**Comment by GriffGreen** [comment]
@fabriziovigevani added it

https://github.com/1Hive/dao-list/pull/35
