### ISSUE TITLE
"Action Collateral" is the name given to both proposal deposit and challenge deposit? Can we have a naming sync?

### ISSUE THREAD

**Issue by laurenluz** [1Hive/gardens#197]
Action Collateral is much more confusing/unclear than proposal deposit and challenge deposit. Also, would be good to have two names for two distinct things.

![image.png](https://images.zenhubusercontent.com/5fdfac16a58523a866ddb68d/4aa31f3d-c80e-4bc2-824b-df892a21d94d)

**Comment by 0xmiel** [comment]
Strongly agree with this. proposal deposit and challenge deposit are better terms

**Comment by 0xmiel** [comment]
I will be attending the TEC params sync today. cc @GriffGreen ^

**Comment by 0xmiel** [comment]
related
https://github.com/1Hive/gardens/issues/178
