### ISSUE TITLE
If a proposal is challenged, is it still able to generate conviction during the settlement period?

### ISSUE THREAD

**Issue by laurenluz** [1Hive/gardens#198]
This proposal has been challenged, is within the settlement period and says that it is "available for execution":

https://gardens-rinkeby.1hive.org/#/garden/0xda1b46663b5ba949f6213d7c3135080b32ad2295/proposal/4

![image.png](https://images.zenhubusercontent.com/5fdfac16a58523a866ddb68d/6cb3c65b-c3e1-4467-8640-3ad4c8172409)

**Comment by 0xGabi** [comment]
We should focus on clarifying and fix that the proposal should not show available for execution.
