### ISSUE TITLE
Supporting a proposal - UI lag can lead to adding more weight than intended

### ISSUE THREAD

**Issue by 0xmiel** [1Hive/gardens#201]
Today, when supporting a proposal, I saw `transaction successfully mined`, but when I closed the confirmation box, I saw that my idle stake hadn't decreased, and my support hadn't been added to the list of supporters (even when refreshing the page) - further,  blockscout couldn't find the transaction.

I incorrectly assumed something had gone wrong, so went through the flow of adding my support again, only for the same thing to happen agian.

It was only once I had completed the process a third time, that the UI registered all three at the same time. So the end result was that I had placed 3x more stake than originally intended.

Is there any way we can solve this? Could we confirm the transaction optimistically on the UI (immediately decrease idle stake and add to list of supporters once transaction has been successfully mined), for example? Or could that have unintended consequences?

**Comment by 0xGabi** [comment]
We added an info box after the tx are mined.
