### ISSUE TITLE
Giveth Garden: Change dynamic issuance from using the total supply to using the circulating supply

### ISSUE THREAD

**Issue by laurenluz** [1Hive/gardens#224]
Hey 1hive! and especially @0xGabi :)

So as you probably know, when we mint the GIV token, some portion of the total supply is going to be subject to the "GIVstream".... basically global vesting where initially those tokens are not able to be claimed/used but they "stream" and become claimable/useable over time (in our case, most likely 5 years).

This creates an issue for the dynamic issuance (as it's currently being used in the gardens) because currently it is based on the total supply. What we need is to have the dynamic issuance depend on the *circulating supply*, i.e. omit the tokens allocated to GIVstream. This could be done if we could simply subtract from the "total supply" the number of tokens that will be held in the vesting contracts.

Can we make this dream a reality?

Following up on behalf of @GriffGreen

**Comment by 0xGabi** [comment]
Sem is currently working on a new version of the issuance app and he will asses the feasibility of this new feature.

**Comment by sembrestels** [comment]
Yes, I think it's totally doable to do a query to an external contract to get the circulating supply. Calculating the circulating supply should not be something that the issuance does, you will need a contract that implements the following interface: 

```
interface ISupplyProvider {
   function getCirculatingSupply(address token) external view returns(uint256);
}
```
It is something that could have sense to be implemented in the GIVstream, or in a totally new contract.

**Comment by GriffGreen** [comment]
yeah we will just not use issuance

**Comment by 0xGabi** [comment]
Cool, Sem mentioned it on the last weekly sync and we closed the issue for now.
