### ISSUE TITLE
Onboarding Review: update banners with new designs

### ISSUE THREAD

**Issue by 0xGabi** [1Hive/gardens#237]

**Comment by fioreb** [comment]
![banner desktop.png](https://images.zenhubusercontent.com/5e5e8c1fc9cab6016da3157e/e5890d03-8eeb-45d5-b3b2-8e68e986208f)![banner mobile.png](https://images.zenhubusercontent.com/5e5e8c1fc9cab6016da3157e/60cb8663-9d13-4551-ada8-0758c9b32b03)![banner tablet.png](https://images.zenhubusercontent.com/5e5e8c1fc9cab6016da3157e/a8054bec-df31-40ec-b761-7e37abfe9424)

Here are the banners. They are very similar to the previous ones but adapted to be more visually similar to the other assets that we have.
