### ISSUE TITLE
Gardens on Rinkeby: update subgraph

### ISSUE THREAD

**Issue by 0xGabi** [1Hive/gardens#241]

**Comment by GriffGreen** [comment]
Yeah!! Lets update that subgraph!! I am excited to play with the GIVgarden!! :-D

**Comment by GriffGreen** [comment]
https://gardens-rinkeby.1hive.org/#/garden/0x38c2c0b72b86858c04352356650ab8cec61d5fc9

^^^ :-D

**Comment by 0xGabi** [comment]
Done with: https://github.com/austintgriffith/scaffold-eth/tree/typescript/packages/vite-app-ts
