### ISSUE TITLE
After reloading page, it says I should enable account ( I enabled before)

### ISSUE THREAD

**Issue by mohammadranjbarz** [1Hive/gardens#252]
**Before reload**
<img width="1435" alt="Screen Shot 1400-05-15 at 22 41 44" src="https://user-images.githubusercontent.com/9850545/128554153-9a9cc2cc-ff33-47f0-bbb9-d2d09cedb36d.png">

**After reload**
<img width="1437" alt="Screen Shot 1400-05-15 at 22 41 55" src="https://user-images.githubusercontent.com/9850545/128554184-f3a518d4-a6b5-44cc-b464-81b0950acb0f.png">

**Comment by 0xGabi** [comment]
Should be addressed with #522

**Comment by 0xGabi** [comment]
We should reuse part of the logic we have on the multichain support: https://github.com/1Hive/honey-pot/pull/522

**Comment by 0xGabi** [comment]
We should extract the logic that prevents this issue while we don't include the multi-chain support. @rperez89 do you want to do it?
