### ISSUE TITLE
Estimated GIV value is "0" for a funding proposal requesting the equivalent of 100 DAI

### ISSUE THREAD

**Issue by laurenluz** [1Hive/gardens#260]
If this were live, I think it would be good if the first line said "This proposal is requesting _approximately 100*_ GIV out of 3,000,000 GIV currently in the common pool."

and it had some tool tip explaining that the actual amount of GIV will be calculated at the time of execution. I don't think the default value for stable amount funding requests should show the equivalent GIV amount as 0 (as in the image below)

![image](https://user-images.githubusercontent.com/75490971/129090333-5ecfe031-f0f9-43b0-bfe0-27ab5c1df485.png)

**Comment by 0xGabi** [comment]
Related to #366

**Comment by 0xGabi** [comment]
Done with: https://github.com/1Hive/gardens-ui/pull/696
