### ISSUE TITLE
"Giveth token" should be simply "GIV"

### ISSUE THREAD

**Issue by laurenluz** [1Hive/gardens#261]
This is a semantic/grammar issue...I'm suggesting to replace "Giveth token" with "GIV"... as it is, it reads funny.

Should say: "This proposal is requesting 0 [GIV] out of 3,000,000 [GIV] currently in the common pool."

![image](https://user-images.githubusercontent.com/75490971/129101536-5bdceb06-ed45-4240-b131-28c0c2ed0ee2.png)

**Comment by laurenluz** [comment]
I think it makes sense to also say "Get GIV" in the header... rather than "Get Giveth token"

![image](https://user-images.githubusercontent.com/75490971/129101948-a6663562-e772-4638-90a2-65841c9441c7.png)

**Comment by 0xGabi** [comment]
Let's default to use the symbol. 

On the top menu bar we can sai: " Giveth <SYMBOL> token from Honeyswap" or similar.
