### ISSUE TITLE
Support this proposal: "Max" button is greyed out when it is clickable

### ISSUE THREAD

**Issue by laurenluz** [1Hive/gardens#262]
It would be better if the "Max" button was green or obviously clickable (if it's clickable)... Right now, it is grey, even though it is clickable.

![image.png](https://images.zenhubusercontent.com/5fdfac16a58523a866ddb68d/20c32d14-aca4-4ecb-8727-34dd4946316b)

**Comment by 0xmiel** [comment]
Not sure I understand here? As it stands, `MAX` is both green and clickable

**Comment by laurenluz** [comment]
ok so "MAX" is green & clickable... but the green is so light in colour that my eyes didn't notice at first 👀 I think this could be better emphasized (though it's not very important)
