### ISSUE TITLE
User notifications for events affecting them

### ISSUE THREAD

**Issue by divine-comedian** [1Hive/gardens#267]
Both my proposals were challenged overnight and visiting the gardens I was not immediately aware of these actions on the homepage. There's some small text in the bottom right of the cards showing the status but those are not easily noticed and as a user being challenged my responses are time sensitive. 

A simple notification panel similar to many UI's would allow users to be notified on the dashboard of actions affecting them. 

![image](https://user-images.githubusercontent.com/67759413/129232720-c7bbfa81-4ecb-475b-993f-ebab1f21fb3c.png)

This is one example from discourse, the ability to see actions affecting you as a user. In Gardens this could be many events such as:  a proposal  receiving additional support, passing or being challenged, as well as if I'm a challenger and the status of my challenge has changed, either settling, forfeiting (no proposer action taken) or escalated to Celeste

**Comment by 0xGabi** [comment]
Close with #632
