### ISSUE TITLE
Add more clickable items on proposal cards

### ISSUE THREAD

**Issue by divine-comedian** [1Hive/gardens#271]
I'm on the main page for my Garden, I see a list of proposals but there's not very many elements clickable on it.

Ideally I should be able to quickly navigate to many places from these proposal cards. 

If I click the proposer's name or profile image I should go to their profile

If I click anywhere in the horizontal area between the title and the `Current Support` bar or the text in the bottom left with the status it should take me to the proposal details screen. 

If I click on the supporters text at the bottom it should show me who supports this proposal, perhaps in a small pop-up modal.

![image](https://user-images.githubusercontent.com/67759413/129387599-6855b724-f172-4505-9c6a-33cfaccc4b41.png)

**Comment by tmoutinho** [comment]
How do you want to show the modal with the supporters when they have more than 50 for example?

**Comment by divine-comedian** [comment]
perhaps it comes up as a small scrollable modal with all of the names?

**Comment by tmoutinho** [comment]
> perhaps it comes up as a small scrollable modal with all of the names?

if the number of supporters if 100 or 500 IMO it makes no sense to show that in a modal. We can show the same as the proposal view 

<img width="358" alt="Captura de ecrã 2022-01-09, às 16 14 42" src="https://user-images.githubusercontent.com/13184907/148690820-8699524b-0b82-497f-8d4d-3b42e1e3d0b2.png">

**Comment by divine-comedian** [comment]
is there any reason that this modal simply couldn't pop up on click of `x supporters` ? 

otherwise perhaps clicking this part simply just takes the user to the detailed view of the proposal

**Comment by tmoutinho** [comment]
> is there any reason that this modal simply couldn't pop up on click of `x supporters` ?

We could show a modal when clicking the x supporters, but what values does it brings to the user? And what it would be a bad user experience to show 100 or more supporters even with a scroll bar to the user, in my opinion of course

**Comment by tmoutinho** [comment]
> otherwise perhaps clicking this part simply just takes the user to the detailed view of the proposal

that would be an easy implement for sure.

**Comment by divine-comedian** [comment]
the nice thing is having a quick view of supporters without navigating to a new page - if you're actively tracking a proposal or a frequent participant in a garden this is a nice to have for sure.

**Comment by tmoutinho** [comment]
> the nice thing is having a quick view of supporters without navigating to a new page - if you're actively tracking a proposal or a frequent participant in a garden this is a nice to have for sure.

Ok, I will work on that then ✌🏻

**Comment by tmoutinho** [comment]
> the nice thing is having a quick view of supporters without navigating to a new page - if you're actively tracking a proposal or a frequent participant in a garden this is a nice to have for sure.

as you can see it works great with small number of supporters, but with 330 it lags.
https://user-images.githubusercontent.com/13184907/148762869-1d8a5501-73e9-4069-9be5-e06910aa9d32.mov

**Comment by 0xGabi** [comment]
close with https://github.com/1Hive/gardens-ui/pull/779
