### ISSUE TITLE
Refactor Covenant button

### ISSUE THREAD

**Issue by 0xGabi** [1Hive/gardens#274]
The Covenant button should be the center point and in the current setout, it does not have an impact. It can be easily missed.

On mobile and tablet sizes the Covenant button does not show.

**Comment by twell-s** [comment]
https://www.figma.com/file/1ykTb399R03n9VKanUZHzK/Gardens-%2BCovenant-Button

**Comment by twell-s** [comment]
Signing the covenant will be the start of the user journey reflected in the welcome/how-to video; if we are able to make the UI modification prior to filming that be great otherwise if we agree on appearance I could edit it in.

**Comment by 0xGabi** [comment]
By the UI modification, do you mean the button changes? I can prioritize working on that! 

The other changes, like the sidebar with the different gardens, are going to take longer.

**Comment by twell-s** [comment]
Yes, just the button change : )

**Comment by rperez89** [comment]
See https://github.com/1Hive/honey-pot/pull/544
