### ISSUE TITLE
Update documentation

### ISSUE THREAD

**Issue by 0xGabi** [1Hive/gardens#278]
The “Documentation” feels impersonal like it is a person who already knows the space rather than “Learn about HNY or Gardens”, yet also gives the sense of a “detailed, sharing the knowledge” approach.

**Comment by divine-comedian** [comment]
hey @0xmiel ! following the Gardens call feel free to add me to this issue if you want to collab.

**Comment by 0xmiel** [comment]
great @divine-comedian . hoping to get started on this next week. will ping you when i do
