### ISSUE TITLE
Create new video content to guide the Garden governance flow

### ISSUE THREAD

**Issue by 0xGabi** [1Hive/gardens#280]
Consider making videos explaining governance and the purpose of Gardens and including it on the landing page.

**Comment by twell-s** [comment]
I've drafted scripts for three ~2-4 min videos:
1. Overview of user flow and features; special emphasis placed on the community covenant and supporting a proposal (easy first steps). 
2. Proposal creation explainer; covers requirements and the difference between suggestion and funding proposals.
3. Proposal challenging explainer; covers requirements, settlement offer period and raising to Celeste.

**Comment by twell-s** [comment]
Scripts can be found [here](https://drive.google.com/drive/folders/1v4dInXpF9b_CDabxjveDXGrswWMKZzvh?usp=sharing).

**Comment by 0xGabi** [comment]
Done with: https://www.youtube.com/watch?v=1ZvXNsLEPAg
