### ISSUE TITLE
Covenant link enhancement

### ISSUE THREAD

**Issue by twell-s** [1Hive/gardens#288]
Encoding community values in the form of a covenant and requiring DAO members to publicly (on-chain) pledge themselves to follow these values is a compelling and unique feature of Gardens and it lies at the heart of Celeste. However, the current UI does not provide a visual signal to new users that indicates an elevated level of importance of the Covenant; at the moment it is in the same visual category as links that take users out of the Gardens app entirely (Get Tokens --> Honeyswap, Stake HNY --> Celeste).

Perhaps we consider enhancing it to appear like a button?
Mock using Fiore's latest UI changes from UX feedback:
https://www.figma.com/file/1ykTb399R03n9VKanUZHzK/Gardens-%2BCovenant-Button?node-id=0%3A1

**Comment by 0xmiel** [comment]
Perhaps we could also have this button stay visible on smaller screens too

**Comment by 0xmiel** [comment]
related https://github.com/1Hive/gardens/issues/274
