### ISSUE TITLE
Landing on Gardens first page- missing parts

### ISSUE THREAD

**Issue by DonnaOftadeh** [1Hive/gardens#291]
![image](https://user-images.githubusercontent.com/53400757/129891457-bcfdbce1-2968-4cfb-8f76-3f856d0c9e34.png)
Browser: Chrome
System:Surface10
When user first land on the page these section
1. Gardens logo is clickable but nothing is gonna happen when click on it, we should either remove the hand sign when hover or make it clickable with a quick visual Guide which pops up.
2. Enable account is not that bold and visible we can use animation or make the icon colourful to make it more visible, also it is not clear why to enable your account on this page
3. The create Garden button is deactivated but it is not clear why (user should enable the account first), it should be clear to the user by be clickable and direct the user to enable account
4. What these , it is not clear that these are the Gardens, a title or wording would be enough I think
5. Stake Honey on the top left, what dose the honey token do with the Gardens, it is not clear

**Comment by 0xmiel** [comment]
Thanks @DonnaOftadeh , this is great feedback

**Comment by 0xGabi** [comment]
We should split this in separate issues.

**Comment by rperez89** [comment]
@0xGabi the create garden button disabled we already solved with the bit of code I did on the multi chain right? You already created a pr for that right ?

**Comment by 0xGabi** [comment]
Yes, we can close this one. I will add a new issue to show the help video when click on the garden homepage logo.
