### ISSUE TITLE
Change support could have better UX

### ISSUE THREAD

**Issue by GriffGreen** [1Hive/gardens#300]
<img width="701" alt="Screen Shot 2021-08-18 at 4 53 59 PM" src="https://user-images.githubusercontent.com/14945613/129921064-81b5f417-e8b6-4efe-8390-19c6e68db5d9.png">

Its confusing that I have to put exactly how many tokens I want to have in the proposal... 
When i put a # of tokens in here... i expected it to be adding to the amount... not to be the total amount

 It would be easier if it were either,

1. Adding or subtracting tokens allocated
2. What % of my holdings are allocated to this proposal

**Comment by 0xmiel** [comment]
related
https://github.com/1Hive/gardens/issues/302
https://github.com/1Hive/gardens/issues/262#issuecomment-901406191
