### ISSUE TITLE
Max button doesn't work (when trying to "change support" on a proposal)

### ISSUE THREAD

**Issue by laurenluz** [1Hive/gardens#302]
related to #262

I staked some tokens on a proposal, then went to change support (add more) but now I can't click the max button... 
![image](https://user-images.githubusercontent.com/75490971/129970903-fd7a4907-0b78-43ba-87cd-603baf687c20.png)

also depending on where my mouse is, I get these arrows, that I also can't click.. they disappear when I click them
![image](https://user-images.githubusercontent.com/75490971/129971069-9bec655b-4a08-43c5-86eb-f7920bd29fec.png)

**Comment by 0xmiel** [comment]
Can't recreate the main issue, though I can recreate the unclickable arrows problem
