### ISSUE TITLE
Docs: add Tao Voting documentation

### ISSUE THREAD

**Issue by 0xGabi** [1Hive/gardens#308]
Quoting Griff:

>🗳 Tao Voting: The Tao Voting App (also a fork of Aragon’s voting app) has a similar use case as Dandelion Voting and will replace Dandelion Voting when the Hatch DAO upgrades to a Commons that uses an Augmented Bonding Curve for issuance and Conviction Voting for fund allocation. Tao Voting has the same powers as Dandelion Voting, but does not include the Ragequit functionality, as that will be done by the Augmented Bonding Curve. It includes three additional features as explained in this forum post:

#1 Delegation: This process would allow token holders to vest their voting powers to a delegate who will cast votes on their behalf. A voter however does not give up full control. The delegates are forced to vote early in the voting period and if the token holder sees that their delegate has voted contrary to the token holder’s will they can veto their vested portion of the delegate’s vote and cast their vote themselves. Both a delegate and a token holder can only vote ONCE.

#2 Disputability: Proposals can be disputed by a challenger, the proposer must respond by either negotiating a settlement or escalating the challenge to Celeste or a form of court and must fork out a token fee to assign and pay jurors to mediate the dispute. Check out this 1hive thread on Celeste for more info.

#3 Wait for Quiet: If a proposal has a change in outcome near the end of the voting period, more time will be added to the end of the voting period so that the token holders that have yet to cast their vote have an opportunity to express their opinion on the controversial proposal.
Features: Vote delegation, disputing proposals, wait for quiet
Governance: Plutocratic, “one token one vote” with delegation. Voting is executed via TEC tokens.

**Comment by divine-comedian** [comment]
This is actually a quote from the documentation I've extensively covered on the TEC forum. 

https://forum.tecommons.org/t/disputable-voting-parameters-general-discussion/267

Happy to take on this issue!

**Comment by 0xGabi** [comment]
Added on the latest Garden documentation.
