### ISSUE TITLE
Homepage stats - total supply:  add the token symbol in parentheses for BYOT gardens

### ISSUE THREAD

**Issue by unixpi** [1Hive/gardens#323]

**Comment by Harthor** [comment]
Where and which token symbol?
Where - I imagine at the right of the number or below, ok?
Which - the token brought? that is also the one that appears at the top left, (or at the left of Common Pool).
Just to make sure we are clear, in this org for example 
https://gardens-rinkeby.1hive.org/#/garden/0xf23d9130a6b41c06a0d4f175da54a1ca319f5681
MTK2 would be what would go in between parenthesis at the right or below the number below total supply.

Just landing into this idea of byot, I would have expected the one showing at the top left was the one native from the garden... maybe it will sink in better with time

**Comment by fabriziovigevani** [comment]
closed by https://github.com/1Hive/gardens-ui/pull/674
