### ISSUE TITLE
App: support for more providers on use-wallet

### ISSUE THREAD

**Issue by 0xGabi** [1Hive/gardens#331]
Tasks related to this issue:

- [x] Update `use-wallet` to latest version `v0.13.0`. Note there was a breaking change on `v0.8.0`.

- [x] Add support for Frame, Wallet Connect, etc

**Comment by 0xGabi** [comment]
Hey @Harthor here is the example repo that @sembrestels mentioned: https://github.com/CommonsSwarm/hatch-app

**Comment by Harthor** [comment]
> Hey @Harthor here is the example repo that @sembrestels mentioned: https://github.com/CommonsSwarm/hatch-app

I just added the same lines from buidler.config.ts (on hatch-app)(which are very few) to hardhat.config.ts (on gardens repo), but i'm not really sure how to test it, if you have any idea, that would help, otherwise i will just keep investigating
