### ISSUE TITLE
Onboarding: add decimal precision to CV sliders

### ISSUE THREAD

**Issue by 0xGabi** [1Hive/gardens#332]

**Comment by Harthor** [comment]
Is this referring to when creating a dao?, add decimal precision to 1 slider or all of them?
<img width="1025" alt="Screen Shot 2021-09-26 at 20 18 14" src="https://user-images.githubusercontent.com/30059114/134827603-391d13e6-c1d8-464a-acd4-8703e3eedb0e.png">
