### ISSUE TITLE
App: add logic to the sidebar to show Gardens with signed covenant

### ISSUE THREAD

**Issue by 0xGabi** [1Hive/gardens#333]
If the user is connected we should display the Gardens that they already signed its covenant.

Related to https://github.com/1Hive/gardens/pull/329

**Comment by rperez89** [comment]
Does this issue replace #294? Or we still need it on the profile page?

**Comment by 0xGabi** [comment]
I think they are related as once we have the sidebar also show on the profile page we should be able to navigate between Gardens.
