### ISSUE TITLE
Landing on Gardens first page- missing parts - section 2 #291

### ISSUE THREAD

**Issue by DonnaOftadeh** [1Hive/gardens#342]
Splitting issue #291 into 2 sections._
Section 2

![image](https://user-images.githubusercontent.com/53400757/132681405-6bc5285e-2527-4586-8b93-c1917b0d213b.png)

4. What are these , it is not clear that these are the Gardens, a title or wording would be enough I think
5. Stake Honey on the top left, what dose the honey token do with the Gardens, it is not clear

**Comment by 0xGabi** [comment]
I think we can close this one as we already addressed 5. And 4 will be improved with #274
