### ISSUE TITLE
GIVGarden page - improvements on UX #294

### ISSUE THREAD

**Issue by DonnaOftadeh** [1Hive/gardens#349]
![project page 1](https://user-images.githubusercontent.com/53400757/132686355-298ba154-d717-4680-9cb4-72ed78705fc1.png)

Griff's suggestion: I would also add that clicking for details shouldn't be so hard... It would be nice that if you clicked anywhere in the 4 box that it would take you to the details page

**Comment by 0xGabi** [comment]
I agree, this is a duplication of #271
