### ISSUE TITLE
Giveth logos cannot be loaded

### ISSUE THREAD

**Issue by DonnaOftadeh** [1Hive/gardens#352]
System: Surface 10
Browser: edge
Giveth Logo both on the first page that user can see all of the gardens and in the Giveth page cannot be loaded
![image](https://user-images.githubusercontent.com/53400757/132852721-ea5791e4-9e16-48a2-984b-cd4c7ccdd9d5.png)
![image](https://user-images.githubusercontent.com/53400757/132852795-3e6f3376-337c-4a05-a776-122493b10364.png)

**Comment by fabriziovigevani** [comment]
closed by https://github.com/1Hive/dao-list/pull/48
