### ISSUE TITLE
网络不好时同时支付3次，系统无法使用

### ISSUE THREAD

**Issue by yibulishou** [1Hive/gardens#429]
![3a466b1986f9e746b8494b30925cc50](https://user-images.githubusercontent.com/86859983/141646865-9a0ca1c8-fdc5-41bb-ab94-2f08ee884f1e.png)

**Comment by yibulishou** [comment]
并且支付不成功

**Comment by 0xGabi** [comment]
This should be fixed now. Thanks for the report!
