### ISSUE TITLE
Design: new asset with Garden branding for the create proposal banner

### ISSUE THREAD

**Issue by 0xGabi** [1Hive/gardens#446]
![Screen Shot 2021-11-21 at 2.28.55 PM.png](https://images.zenhubusercontent.com/5bc8415c6bda4c5abfa544f3/d4b2eddd-fbfb-4874-9157-f8ad60b3a988)

**Comment by fioreb** [comment]
Here is the figma file with the designs:
https://www.figma.com/file/CThGCg5Yeu2PM8fr0NZKxV/Feed-gardens-banner-for-V1?node-id=0%3A1

And a folder that contains all the banners :
[https://app.zenhub.com/files/353881841/00559861-35c5-4dcf-baea-c1979af08a69/download](https://app.zenhub.com/files/353881841/00559861-35c5-4dcf-baea-c1979af08a69/download)

**Comment by 0xGabi** [comment]
done with https://github.com/1Hive/honey-pot/pull/703
