### ISSUE TITLE
Delegated voting UI changes

### ISSUE THREAD

**Issue by fioreb** [1Hive/gardens#462]
Here you can find the designs for the Delegate voting section, I did it super simple for the v1 release:
https://www.figma.com/file/OksvE2Qph3TOh8sxBwu7dO/Delegate-voting?node-id=0%3A1

And the new icon for the user menu:
![Delegate voting.svg](https://images.zenhubusercontent.com/5e5e8c1fc9cab6016da3157e/a2f8510b-8607-449e-a573-cbd439bb7133)

**Comment by rperez89** [comment]
We need to re think this screen  according to what was talked on the  last  planning
