### ISSUE TITLE
App (UX): refactor Abstain proposal

### ISSUE THREAD

**Issue by 0xGabi** [1Hive/gardens#465]
We should do a better job at explaining the effects the abstain proposal has on the system and create a special card for this special signaling proposal. 

Figma with designs:

https://www.figma.com/file/epNKnVEcJd5CzGFXpnFMtx/Abstain-proposal?node-id=1%3A2850

Abstain icon:

![abstain_icon](https://user-images.githubusercontent.com/9082013/150564774-c9c44fe3-0a5f-48aa-bdc5-33907ad79fbc.svg)

**Comment by 0xGabi** [comment]
@tmoutinho we can also edit the details card section. Using the same icon and name. And removing the forum, status, and create by values because they are not relevant here.


<img width="1244" alt="Screen Shot 2022-01-21 at 3 12 40 PM" src="https://user-images.githubusercontent.com/9082013/150579434-4c97a5ce-7176-486c-8114-4d2efd2b9574.png">

**Comment by tmoutinho** [comment]
Sure @0xGabi, I will do that ✌️

**Comment by 0xGabi** [comment]
close with https://github.com/1Hive/gardens-ui/pull/807
