### ISSUE TITLE
Onboarding Spending Limit input ignored decimal?

### ISSUE THREAD

**Issue by GriffGreen** [1Hive/gardens#480]
The GIVgarden passes proposals at an ungodly speed... 

<img width="1181" alt="Screen Shot 2021-12-07 at 9 26 18 PM" src="https://user-images.githubusercontent.com/14945613/145143091-fefb27c8-7532-4ef5-8119-51631a49ba57.png">

I can take 95% of the money out of the DAO with 0.01% of the Effective Supply... it's broken!

I think we put in 2.50% for the spending limit ... but it was read as 250%

https://blockscout.com/xdai/mainnet/address/0x692A37C6A523D373198dEc738410B5BFFEcc12c0/read-proxy

Might be worth checking how the Onboarding dapp plays with decimals

**Comment by fabriziovigevani** [comment]
Did this by any chance appear for a few seconds? It´s definitely on the proposal detail side but can´t find where from.

Just took a look and i see it´s showing accordingly now. 
![Screen Shot 2021-12-09 at 17 30 45](https://user-images.githubusercontent.com/22663232/145471204-87cb2dae-1f01-45d8-a7ca-1eab66d123bc.png)

**Comment by 0xGabi** [comment]
Maybe similar issue that was solve heer: https://github.com/1Hive/gardens-ui/pull/743

**Comment by 0xGabi** [comment]
Should be fixed with [#88](https://github.com/1Hive/gardens-ui/pull/883)
