### ISSUE TITLE
Cannot add email, twitter, or github account to my profile in the GIVgarden

### ISSUE THREAD

**Issue by WhyldWanderer** [1Hive/gardens#482]
Testing GIVgarden: https://gardens-staging.1hive.org/#/xdai/garden/0x2050eabe84409e480ad1062001fdb6dfbc836192

I am unable to add my email, twitter, or github account to my profile in the garden.

![image](https://user-images.githubusercontent.com/74267818/145249122-522b6803-09b6-4292-9937-6f25ef41c7ac.png)

The fields are there but I cannot click them or type in them.

**Comment by fabriziovigevani** [comment]
Yes, this is a known issue that we will handle when refactoring the profiles. We should start soonish with this.

For the moment we placed an Info box stating to verify your identities through the 3box dapp

**Comment by 0xGabi** [comment]
We will address it with #48
