### ISSUE TITLE
Conversion numbers are incorrect - GIVgarden testing

### ISSUE THREAD

**Issue by WhyldWanderer** [1Hive/gardens#483]
At the time that I made the proposal, TestGIV was valued at 0.39. 
![image](https://user-images.githubusercontent.com/74267818/145251134-17069179-842c-4478-b608-bb4bf26f8432.png)

But the math does not add up when creating a new proposal.
![image](https://user-images.githubusercontent.com/74267818/145250764-b2d21c42-16ad-464b-8ef5-6a46e7220b69.png)

**Comment by 0xGabi** [comment]
This is not an issue on the UI but because the oracle was not called with enough frequency. Each garden should run the service under: https://github.com/1Hive/price-oracle-service
