### ISSUE TITLE
Delegate button will click when it doesnt work, maybe it should be greyed out if it doesnt work 

### ISSUE THREAD

**Issue by GriffGreen** [1Hive/gardens#484]
<img width="370" alt="Screen Shot 2021-12-09 at 7 19 52 AM" src="https://user-images.githubusercontent.com/14945613/145403834-f1b43882-78a8-4703-b14d-782586c9ac4f.png">

https://gardens-staging.1hive.org/#/xdai/garden/0x2050eabe84409e480ad1062001fdb6dfbc836192/

<img width="580" alt="Screen Shot 2021-12-09 at 7 22 07 AM" src="https://user-images.githubusercontent.com/14945613/145404141-b6f10acb-42c7-4680-bf7c-c53a4080aa70.png">

It took maybe 5 minutes after wrapping for it to work

So not much of a technical issue... more of a UX issue

**Comment by fabriziovigevani** [comment]
Doesn´t work in that it doesn´t pop up the modal when clicking the button or did you get an error after entering your delegate´s address and clicking `Delegate` button ?
Those errors don´t seem to be related with the issue actually.

**Comment by laurenluz** [comment]
It doesn't pop up the modal when clicking the button.

It's ok for me, but we had two people testing today reporting the same issue. They were both signed in and had wrapped tokens already.
