### ISSUE TITLE
Price oracle in the GIVgarden is not functioning

### ISSUE THREAD

**Issue by WhyldWanderer** [1Hive/gardens#497]
![image](https://user-images.githubusercontent.com/74267818/147375428-445daf5e-6875-439e-95d4-31f8f017cf40.png)

![image](https://user-images.githubusercontent.com/74267818/147375429-cf765505-7078-488a-b696-8674a53007e0.png)

**Comment by kamikazebr** [comment]
Hi @WhyldWanderer it errors still occours?

I made test here - https://dashboard.tenderly.co/tx/xdai/0x575a2a605228bec93883b2ced2ac04aee6ddcd0409bcb7c735e41388228b5af9

It get updated

https://gardens.1hive.org/#/xdai/garden/0xb25f0ee2d26461e2b5b3d3ddafe197a0da677b98

if could check if still, in case error sent us the tx hash to investigate :D

**Comment by laurenluz** [comment]
I think it's working well now!!

**Comment by kamikazebr** [comment]
Awesome! Tyvm @laurenluz. i'm closing that issue.
