### ISSUE TITLE
Can we add Torus as a compatible wallet for the garden?

### ISSUE THREAD

**Issue by laurenluz** [1Hive/gardens#499]
app.tor.us

Many Giveth users have torus wallet - it's a really easy web2-esque way of getting a crypto wallet... and we'd love it if projects who get GIV in their Torus wallets could participate in the GIVgarden.

**Comment by kamikazebr** [comment]
Some refs:

https://github.com/torusresearch/torus-embed/tree/master/examples/react-basic-app/src

Docs:
https://docs.tor.us/wallet/api-reference/installation

And looks like useWeb3React has already integrated Torus Connector, our useWallet use that, so need investigate the compatibility with Metamask to keep the UX the same using Torus

https://github.com/NoahZinsmeister/web3-react/blob/v6/packages/torus-connector/src/index.ts

**Comment by 0xGabi** [comment]
@laurenluz would you mind doing some tests here: https://gardens-ui-git-integrate-torus-1hive.vercel.app/#/home

And share the feedback with us before we decide to merge the changes. Thanks!

**Comment by laurenluz** [comment]
Hey @0xGabi Awesome! Happy to help...

I just tried to sign in w my Torus through and it says my account is not enabled... even though at the bottom is appears to be connected.
![image](https://user-images.githubusercontent.com/75490971/156432947-28758b27-a32b-408d-a989-8fac447b0750.png)

**Comment by 0xGabi** [comment]
Thank you for sharing Lauren. We will investigate. And we are still discussing if we would like to include torus as a new provider or not.

**Comment by laurenluz** [comment]
haha ok booooo. it makes sense. but booooo 🤣
