### ISSUE TITLE
Onboarding: we should check the name being used was not already register on AragonID

### ISSUE THREAD

**Issue by 0xGabi** [1Hive/gardens#505]
Otherwise, the user will do the whole onboarding until the last transaction where the AragonID domain is registered and it will fail.

Transaction example: https://dashboard.tenderly.co/1Hive/gardens/tx/rinkeby/0xe8a2a20e809f998be4ef7ec095d3061f63ed5b09051b8454ddb891840c916f18

**Comment by kamikazebr** [comment]
I got that error when recovering the onboarding wizard from localstore.

So if my internet its slow or i click to next button fast enough it dont have time to check if address exist.
