### ISSUE TITLE
Celeste: services are not working for Polygon network

### ISSUE THREAD

**Issue by 0xGabi** [1Hive/gardens#508]
- [x] Fixed the subscribe email in the notification service 
- [x] Fixed some services to rinkeby and polygon network - more specific the Ingress
- [ ] Update the subgraph https://github.com/1Hive/celeste-subgraph , Rinkeby is not loading the dashboard
- [ ] Investigate why has accumulated numbers of transactions goes altho of `heartbeat()` function
- [ ] Try reset the numbers
- [ ] Find the contract address `Court` and check if it's correct in the Pods
- [ ] Fix the `localhost:8545` error in dashboard.

**Comment by kamikazebr** [comment]
I'm taking look in @rperez89, posted some updates in Celeste Swarm

**Comment by kamikazebr** [comment]
Need refill some ETH on the wallets

**Comment by kamikazebr** [comment]
Fixed the Email service, but need check if /dispute its correct across networks.

**Comment by 0xGabi** [comment]
Replace by https://github.com/1Hive/gardens-ui/issues/821
