### ISSUE TITLE
Gardens votes that can't be executed should be able to be hidden from view after a day

### ISSUE THREAD

**Issue by GriffGreen** [1Hive/gardens#511]
The TEC made a bad vote with evmCrispr that we can't execute... i don't think this will be a rare thing... anyone who sees this vote will waste their gas money and their time reviewing and executing... and it will clutter the UI 

https://gardens.1hive.org/#/xdai/garden/0x1fc7e8d8e4bbbef77a4d035aec189373b52125a8

![Screen Shot 2022-01-13 at 11 15 32 AM](https://user-images.githubusercontent.com/14945613/149377317-3cf350c5-91e8-4046-90e5-e8562835d652.png)

**Comment by rperez89** [comment]
> The TEC made a bad vote with evmCrispr that we can't execute... i don't think this will be a rare thing... anyone who sees this vote will waste their gas money and their time reviewing and executing... and it will clutter the UI
> 
> https://gardens.1hive.org/#/xdai/garden/0x1fc7e8d8e4bbbef77a4d035aec189373b52125a8
> 
> ![Screen Shot 2022-01-13 at 11 15 32 AM](https://user-images.githubusercontent.com/14945613/149377317-3cf350c5-91e8-4046-90e5-e8562835d652.png)

once this get merged <https://github.com/1Hive/gardens-ui/pull/819> we can start adding `decisionsVoided` into the dao list repo to void disputes, wondering if in order for us to really get a voided decision we should ask the community to create a suggestion vote and if it gets enought support we add that entry to the list
