### ISSUE TITLE
can't update covenant 

### ISSUE THREAD

**Issue by divine-comedian** [1Hive/gardens#513]
Try to update our gardens covenant on staging the vote passes but the transaction continues to fail, I have tried increasing the gas amounts several times - here is some more data 

the vote - https://gardens-staging.1hive.org/#/xdai/garden/0x16388d99199a74810fc572049b3d4d657e7d5deb/vote/5

the failed transaction - https://dashboard.tenderly.co/tx/xdai/0x4d8153d146b743c8f8a94d2f82937e0fceae2590dec1441683c8fb4595e40811

the script ran via EVM crispr v0.3.3 - 
```
connect 0x16388D99199A74810fc572049b3d4D657e7D5deB disputable-voting.open @context:updating covenant
exec agreement.open changeSetting 0x44e4fcfed14e1285c9e0f6eae77d5fdd0f196f85 false "Giveth Community Covenant" 0x516d506e5a37534b374a7966476b71686e414a3877415076655773337a6568774c754c4459755931444e42477341
```

intial discussions point to the problem that AppFeesCashier is set to true even when you specify it as false via the script. 

discussion on discord - https://discord.com/channels/698287700834517064/754870015357878304/930893379003383818

**Comment by 0xGabi** [comment]
Fix with https://github.com/1Hive/gardens-ui/pull/805
