### ISSUE TITLE
Transaction fails while adding funds to deposit manager

### ISSUE THREAD

**Issue by 0xGabi** [1Hive/gardens#522]
Garden on Polygon that is failing: https://gardens.1hive.org/#/matic/garden/0x3309de3ed60e609d8542835aa732aebadda85171/collateral/deposit  

Attached "transaction failed" error

![error](https://user-images.githubusercontent.com/9082013/151887162-4e610f2c-862a-429f-8a0e-40ec189cc395.png)

**Comment by kamikazebr** [comment]
https://polygonscan.com/tx/0x38fb53fc5414b3101c3351735a8b4a239d2bb006edf0246eb6629b686b36be6c - tx link

**Comment by kamikazebr** [comment]
The screen should allow you add funds same with 0 the balance?

![image](https://user-images.githubusercontent.com/691510/152089982-2b4b471c-b329-4c38-872d-c4ed24e527de.png)

@0xGabi

**Comment by 0xGabi** [comment]
As I understand this issue is related to the second point of https://github.com/1Hive/gardens-ui/issues/826:
 
The deposit manager modal does not validate requirements.  `approve` step omitted

**Comment by rperez89** [comment]
Thttps://github.com/1Hive/gardens-ui/pull/844 might solve the issue

**Comment by kamikazebr** [comment]
Yah i believe yes too.
