### ISSUE TITLE
Add support for visualization of stakes per garden on profile

### ISSUE THREAD

**Issue by 0xGabi** [1Hive/gardens#523]
The current profile does not discriminate supported proposal per Garden instead shows all the supported proposals grouped in the same component.

<img width="304" alt="Screen Shot 2022-02-01 at 12 06 04 PM" src="https://user-images.githubusercontent.com/9082013/151993992-9d93ad1f-d4d8-4058-bf25-e17470f218db.png">

**Comment by tmoutinho** [comment]
Hey @0xGabi , Do we have an ideia for the design?  I have done the code regarding the stakes array.

<img width="1438" alt="Captura de ecrã 2022-02-27, às 21 01 20" src="https://user-images.githubusercontent.com/13184907/155899823-01486061-97e0-4a52-8752-3e9521db6735.png">

**Comment by rperez89** [comment]
closed with <https://github.com/1Hive/gardens-ui/pull/834>
