### ISSUE TITLE
UPDATE REQUEST - River Coop Garden

### ISSUE THREAD

**Issue by pglavin2** [1Hive/gardens#524]
Name of Garden:  River
Discord User:  Patrick-River
New Garden Description:  A nonprofit, cooperative process for funding social & environmental impact initiatives.
New Token Logo (link):  https://drive.google.com/file/d/112_lMpKYBp7ON873AkEuuMC0K4C0oSLV/view?usp=sharing
New Logo with Name (link): https://drive.google.com/file/d/1NmRBSEGIWLkbd1buLL3ILc_dMAtnXw_S/view?usp=sharing
New Link to your Wiki:  https://wiki.river.coop/
New Additional Links:  website - https://river.coop/

**Comment by 0xGabi** [comment]
Done!
