### ISSUE TITLE
UPDATE REQUEST - Gardens DAO info for GAIAC 

### ISSUE THREAD

**Issue by pglavin2** [1Hive/gardens#525]
**Garden Name:**  GAIAC
**Discord User:**  Curtis#4847

**New Garden Name:**  Gaia Garden
**New Garden Description:**  Connecting the blockchain to the environment through people
**New Token Logo:**  https://static.wixstatic.com/media/28c079_d4ed0a36a45b4e699624cef3b0d461d2~mv2.png/v1/fill/w_112,h_112,al_c,q_85,usm_0.66_1.00_0.01/Gaia%20Coin%20Logo.webp
**New Logo:**  https://static.wixstatic.com/media/28c079_d4ed0a36a45b4e699624cef3b0d461d2~mv2.png/v1/fill/w_112,h_112,al_c,q_85,usm_0.66_1.00_0.01/Gaia%20Coin%20Logo.webp
**New Logo with Name:**  https://ibb.co/YNssbsL
**New Link to your Wiki:**  http://www.gaiacoin.org/
**New Link to your Forum:**  https://www.gaiacoin.org/group/gaia-coin-foundation-group/discussion
**New Additional Links:**  Discord  https://discord.gg/6Vj5wQPC

**Comment by 0xGabi** [comment]
Done!
