### ISSUE TITLE
I staked my tokens, but I can't withdraw them now, the webpage keeps prompting an error

### ISSUE THREAD

**Issue by yibulishou** [1Hive/gardens#526]
I staked my tokens, but I can't withdraw them now, the webpage keeps prompting an error
this is address
https://gardens.1hive.org/#/garden/0x1e2d5fb385e2eae45bd42357e426507a63597397/

**Comment by tjayrush** [comment]
I'm seeing this same behavour. I created a proposal and then canceled it. It seems I can't get my 5,000 GIV back. The topmost balance shows >5000 GIV, but when I go into create a new proposal, the 5000 is not available. Here's a picture of what I'm seeing: https://forum.giveth.io/t/proposal-draft-monitoring-tool-to-help-identify-and-mitigate-recirculating-givbacks/405/13?u=tjayrush.

Here's the profile I'm having trouble with: https://gardens.1hive.org/#/xdai/garden/0xb25f0ee2d26461e2b5b3d3ddafe197a0da677b98/collateral/deposit

Here's the proposal: https://gardens.1hive.org/#/xdai/garden/0xb25f0ee2d26461e2b5b3d3ddafe197a0da677b98/proposal/17

**Comment by tjayrush** [comment]
I found that I had to first 'unwrap' the 5,000 tokens and then it allows me to proceed. I was able to proceed after unwrapping.

**Comment by rperez89** [comment]
> I staked my tokens, but I can't withdraw them now, the webpage keeps prompting an error this is address https://gardens.1hive.org/#/garden/0x1e2d5fb385e2eae45bd42357e426507a63597397/

is this still happening? ia am able to wrap and unwrap without any issue in this garden, if still happening can you share a video and check if there is some error being displayed on the console?

**Comment by tjayrush** [comment]
I was able to create the new proposal but only after I unwrapped and then re-wrapped the tokens. It was either that, or I just waited a day and then it was possible. Not sure. You may close this if you wish.

**Comment by rperez89** [comment]
Since seems  that you were able to proceed going to close this one, feel free to open a new one if something else happens
