### ISSUE TITLE
Something went wrong / unexpected error has occurred

### ISSUE THREAD

**Issue by freshelle** [1Hive/gardens#530]
I'm trying to access Giveth gardens, but this error message always prompts. I wonder if there's an action needed on my end

<img width="611" alt="image" src="https://user-images.githubusercontent.com/86718721/157816842-9ee5fd3f-2389-48a1-96da-9f382dba7d95.png">
<img width="1435" alt="image" src="https://user-images.githubusercontent.com/86718721/157817017-b401bd6b-d09e-4448-ba62-e972227221bc.png">

**Comment by rperez89** [comment]
> I'm trying to access Giveth gardens, but this error message always prompts. I wonder if there's an action needed on my end
> 
> <img alt="image" width="611" src="https://user-images.githubusercontent.com/86718721/157816842-9ee5fd3f-2389-48a1-96da-9f382dba7d95.png">
> 
> <img alt="image" width="1435" src="https://user-images.githubusercontent.com/86718721/157817017-b401bd6b-d09e-4448-ba62-e972227221bc.png">

@freshelle  is this still happening? sometimes happens because of the rpc being not working, i can access fin here

**Comment by freshelle** [comment]
Yes. I think I have an ipfs problem and it's just probably something to fix on my end.

<img width="1433" alt="image" src="https://user-images.githubusercontent.com/86718721/159211034-133fb684-5877-4912-8694-9002f4f5892f.png">

**Comment by rperez89** [comment]
ah , try with another browser or let us know if you need some help if still happening, going to close this issue feel free to open a new one if still happening
