### ISSUE TITLE
After removing a proposal, I recreated a new proposal with the same forum link, but the form won't allow me to create the new proposal

### ISSUE THREAD

**Issue by tjayrush** [1Hive/gardens#532]
I had a previous proposal (#17) on the Giveth Garden which I removed (due to an incorrect amount asked for).

When I tried to create a new proposal using the same link to the original forum, the Proposal dialog tells me "Forum post link not provided or not valid" and greys out the 'Continue' button, even though the link I'm using (https://forum.giveth.io/t/proposal-draft-monitoring-tool-to-help-identify-and-mitigate-recirculating-givbacks/405) is clearly correct.

This makes it impossible to proceed.

![image](https://user-images.githubusercontent.com/5417918/158390583-90589dc1-1f56-4624-b933-06b76b2afc98.png)

**Comment by rperez89** [comment]
will take a look thanks @tjayrush

**Comment by tjayrush** [comment]
For some reason, after a certain amount of time, it seems to have corrected itself. I was able to create the proposal a day or two later with no problem. You can close this on my account, but if you want to keep it open, no problem.

**Comment by rperez89** [comment]
> For some reason, after a certain amount of time, it seems to have corrected itself. I was able to create the proposal a day or two later with no problem. You can close this on my account, but if you want to keep it open, no problem.

oh strange, let us know if this happens again, thxs!
