### ISSUE TITLE
Trying to execute with EVM Crisper in the same way as I usually do, but scientific notation doesnt work any more

### ISSUE THREAD

**Issue by GriffGreen** [1Hive/gardens#544]
<img width="742" alt="Screen Shot 2022-04-19 at 12 44 32 PM" src="https://user-images.githubusercontent.com/14945613/164064060-0a847c9f-ca88-4337-8a58-1464decabdd1.png">

This failed:

<img width="1549" alt="Screen Shot 2022-04-19 at 12 43 35 PM" src="https://user-images.githubusercontent.com/14945613/164064968-c2a02640-ad9a-4df7-a4ff-cf34c4546825.png">

Figured it out that it was the scientific notation... but it used to work like that any more

**Comment by rperez89** [comment]
@sembrestels was that feature removed? @GriffGreen have you tried with `e` instead of `E` ?

**Comment by GriffGreen** [comment]
I'll try with lower case e next time and see... maybe that was the issue

**Comment by rperez89** [comment]
Ok feel free to open the issue again if stills happens
