### ISSUE TITLE
Context that got added turns into a link that doesnt work

### ISSUE THREAD

**Issue by GriffGreen** [1Hive/gardens#545]
https://gardens.1hive.org/#/xdai/garden/0x1fc7e8d8e4bbbef77a4d035aec189373b52125a8/vote/9

When you scroll over "Read Description" the link is: 

https://gardens.1hive.org/Update%20the%20Entry%20Tribute%20from%2014%%20to%2012%%20and%20update%20the%20Exit%20Tribute%20from%206%%20to%207%%20%20https://forum.tecommons.org/t/goldilocks-proposed-tribute-adjustments/862/12

<img width="814" alt="Screen Shot 2022-04-19 at 12 51 35 PM" src="https://user-images.githubusercontent.com/14945613/164065315-f0a41937-3cf4-4285-9792-eebe68c480eb.png">

**Comment by rperez89** [comment]
> https://gardens.1hive.org/#/xdai/garden/0x1fc7e8d8e4bbbef77a4d035aec189373b52125a8/vote/9
> 
> When you scroll over "Read Description" the link is:
> 
> https://gardens.1hive.org/Update%20the%20Entry%20Tribute%20from%2014%%20to%2012%%20and%20update%20the%20Exit%20Tribute%20from%206%%20to%207%%20%20https://forum.tecommons.org/t/goldilocks-proposed-tribute-adjustments/862/12
> 
> <img alt="Screen Shot 2022-04-19 at 12 51 35 PM" width="814" src="https://user-images.githubusercontent.com/14945613/164065315-f0a41937-3cf4-4285-9792-eebe68c480eb.png">

Thanks will take a look

**Comment by rperez89** [comment]
@GriffGreen seems that you wrote all this on the context field `"Update the Entry Tribute from 14% to 12% and update the Exit Tribute from 6% to 7%  https://forum.tecommons.org/t/goldilocks-proposed-tribute-adjustments/862/12"` instead of just the forum url? `https://forum.tecommons.org/t/goldilocks-proposed-tribute-adjustments/862/12`

**Comment by GriffGreen** [comment]
yes! I did. Sorry i didn't know I could only add a link...

**Comment by rperez89** [comment]
Good point, going to add a help icon to clarify this thxs!
