### ISSUE TITLE
Error in Accessing Page

### ISSUE THREAD

**Issue by missgene** [1Hive/gardens#546]
My wallet is already connected gardens.1hive.org but I still cannot access the page. I tried disconnecting and reconnecting my wallet, but it still didn't work. 

![image](https://user-images.githubusercontent.com/93360299/164123919-61d3942b-d893-4704-9d00-05154bf57597.png)

![image](https://user-images.githubusercontent.com/93360299/164123978-fd92fe22-a1ef-4069-a0a2-a098572fe441.png)

I've repeatedly refreshed these pages:
https://gardens.1hive.org/#/xdai/garden/0xb25f0ee2d26461e2b5b3d3ddafe197a0da677b98  
https://gardens.1hive.org/#/xdai/garden/0x1fc7e8d8e4bbbef77a4d035aec189373b52125a8  

I cannot also close the Error dialog box..

**Comment by Corantin** [comment]
Up 👍

**Comment by rperez89** [comment]
Closing since seems that was an rpc issue at the time you did the requests
