### ISSUE TITLE
An unexpected error has occurred

### ISSUE THREAD

**Issue by Corantin** [1Hive/gardens#547]
![image](https://user-images.githubusercontent.com/13890618/164475546-ec4b430f-2e8b-4ec1-822a-1c33c2392521.png)

Browser : Problem occurs with Chrome and Brave

Repro steps : 
- Access a proposal by url being connected
- Bee spinner and header showing my account is connected
- `An unexpected error has occurred` Popup
- Reload does not fix

_Not repoducing when not connected_

I also have this bug in main page (not sure if it's related or not) : https://github.com/1Hive/gardens/issues/546

Here is the error detail stack trace :
`Cannot read properties of undefined (reading 'find')
in an
in Hn
in Mn
in t
in t
in p
in f
in t
in Suspense
in t
in Ie
in div
in t
in Layout___StyledDiv
in w
in t
in Layout___StyledLayout
in Pe
in div
in t
in MainView___StyledDiv5
in div
in t
in MainView___StyledDiv4
in div
in t
in ScrollView___StyledDiv
in ge
in div
in c
in t
in MainView___StyledRootProvider
in div
in t
in MainView___StyledDiv2
in div
in t
in MainView___StyledDiv
in i
in t
in MainView___StyledToastHub
in Qs
in m
in C
in D
in A
in L
in F
in Q
in Y
in R
in u
in v
in a
in m
in Le
in Unknown
in Ue
in w
in i
in R
in i
in i
in div
in c
in Ee
in Provider
in xe
in t
in r
in Cu`

**Comment by Corantin** [comment]
https://gardens.1hive.org/#/xdai/garden/0x8ccbeab14b5ac4a431fffc39f4bec4089020a155/proposal/90

**Comment by Corantin** [comment]
Here is the har file with all the requests :
[gardens.1hive.org.zip](https://github.com/1Hive/gardens/files/8555600/gardens.1hive.org.zip)

**Comment by Corantin** [comment]
Works with my phone

**Comment by rperez89** [comment]
yeah i think you might have some issue with your environment. Not able to reproduce on my end. Do you know if somebody else is having the same issue?

<img width="1675" alt="Screen Shot 2022-04-29 at 2 16 12 PM" src="https://user-images.githubusercontent.com/11763623/165992216-d1aaf640-da2b-4345-b420-a0b779d1a64f.png">
