### ISSUE TITLE
Add update Oracle price functionality to Honey Pot

### ISSUE THREAD

**Issue by fioreb** [1Hive/gardens#83]
It should say "Oracle price" with a tooltip explaining "This is the price used for funding proposals defined in xDAI. Calling update price could return a reward." the price should be below or close by and a button "Update"/"Update price" or whatever you think which creates a transaction. It will be greyed out when it doesn't need to be clicked (it only needs to be clicked once every 3 hours).

**Comment by fioreb** [comment]
Here are the designs: https://www.figma.com/file/P06HTzSyb9hExJVpwaUPmA/Honey-Pot-2.0?node-id=3146%3A18562

**Comment by 0xGabi** [comment]
Thanks @fioreb
